services:
  auth-service:
    build:
      context: .  # <--- Titik pusat adalah root folder
      dockerfile: auth-service/Dockerfile # <--- Lokasi Dockerfile-nya
    ports:
      - "8086:8080"

  notification-service:
    build:
      context: .  # <--- Sama, titik pusat di root
      dockerfile: notification-service/Dockerfile
    ports:
      - "8087:8080"